#!/bin/bash

CURDIR=$( cd "$( dirname "$0" )" && pwd );
MAINDIR=$( dirname "$CURDIR" )

# Check dependencies URL and version 
URL=(); 
TAG=(); 
for name in ${MAINDIR}/../dependencies/cmake/geometry/* \
            ${MAINDIR}/../dependencies/cmake/video/*; do 
  URL+=( $( cat $name | grep GIT_REPOSITORY | awk '{print $2}' ) ); 
  TAG+=( $( cat $name | grep GIT_TAG        | awk '{print $2}' ) ); 
done 
URL+=( https:/vcgit.hhi.fraunhofer.de/jvet/HM.git              ); TAG+=( HM-16.21+SCM-8.8 )
URL+=( https:/vcgit.hhi.fraunhofer.de/jvet/VVCSoftware_VTM.git ); TAG+=( VTM-13.0 )

echo -e \
	"\n\n<!--- \n" \
	"  ############################################################### \n" \
	"  # File automatically generated by $0 # \n" \
	"  # do not edit manually.                                       # \n" \
	"  ############################################################### \n" \
	"--> \n\n"  
echo -e "## Dependencies\n\n"  
echo -e "The V-DMC test model software uses several dependencies that \
are cloned and patched by the CMake building process. \n\n These dependencies are: \n\n" 

for ((i=0;i<${#URL[@]};i++)); 
do 
	if [ $i == 0 ] ; then printf "| **URL** | **Commit/tag** | \n|---|---| \n"  ; fi	
  printf "| [%-20s](%-70s) | %-s | \n" $( basename ${URL[$i]%.???} ) ${URL[$i]} ${TAG[$i]}; 
done
