"""Train a ReRF feature-voxel sequence over a prepared NeVo corpus.

Generates an mmcv config under ``rerf/configs/nevo/`` and drives upstream's
``run.py`` with the environment it expects (see ``nevo.rerf_env``). One
invocation trains frames ``[start, end)`` of one object; the per-frame
structure ReRF produces is

    fine_last_0.tar              I-frame: absolute density + feature grid
    fine_last_<n>_deform.tar     P-frame motion vectors (deformation_field)
    fine_last_<n>.tar            P-frame residual features over the warped
                                 previous frame

which is exactly the I/P group-of-features layout NeVo's step 1 reads back.

Deliberate deviations from upstream's ``configs/rerf/kpop.py``, both about
fitting this box rather than about the method:

* ``num_voxels`` defaults to 160^3 (DVGO's own default) rather than kpop's
  250^3. At 250^3 one frame's checkpoints run ~1.5 GB and a 30-frame sequence
  of three objects would not fit in the 81 GB free on this machine's root
  filesystem. Pass ``--num-voxels 250`` to match the paper's setting.
* ``N_iters`` defaults below kpop's 16000 because our corpus is 48 synthetic
  views of a rigidly-calibrated rig with exact poses and a clean matte, which
  converges faster than 76 real cameras. ``--iters`` restores it.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

MODULE_ROOT = Path(__file__).resolve().parents[1]
if str(MODULE_ROOT) not in sys.path:
    sys.path.insert(0, str(MODULE_ROOT))

from nevo.rerf_env import RERF_ROOT  # noqa: E402

CONFIG_DIR = RERF_ROOT / "configs" / "nevo"

CONFIG_TEMPLATE = '''# Generated by baselines/NeVo/orbitnevo/train.py -- edits will be overwritten.
_base_ = '../default.py'

expname = {expname!r}
basedir = {basedir!r}
half_res = True

# ReRF's group-of-features structure: one I-frame followed by motion-vector +
# residual P-frames. 'individual' keeps each frame's grid a separate model
# (rather than co-training a window of frames), which is what the streaming
# decoder consumes one frame at a time.
train_mode = 'individual'
fix_rgbnet = True
deform_res_mode = "separate"
res_lambda = 1e-2
deform_lambda = 1e-2
frame_num = {frame_num}
deform_low_reso = True
density_deform = False
deform_from_start = True

data = dict(
    datadir={datadir!r},
    dataset_type='NHR',
    # OpenCV camera convention (y down, z forward): what prepare.py writes into
    # cams_<frame>.json, and what ReRF's own NHR corpus uses.
    inverse_y=True,
    # Our renders are RGB over black with a separate coverage mask, and the
    # loader composites them onto this background before training.
    #
    # Black, to match the corpus and `baselines/Vega`. Compositing onto white
    # instead teaches the model semi-transparent whitish content at the
    # silhouette, which is invisible against a white background and shows up as
    # a bright fringe the moment anything is rendered against black. It also
    # makes NeVo's pixels non-comparable with Vega's, which trains on the
    # corpus's native black.
    white_bkgd={white_bkgd},
)

coarse_train = dict(
    N_iters={coarse_iters},
    N_iters_pretrained={coarse_iters_p},
)

fine_train = dict(
    N_iters={fine_iters},
    N_iters_pretrained={fine_iters_p},
    tv_every=1,
    tv_after=1000,
    tv_before={tv_before},
    tv_dense_before={tv_before},
    weight_tv_deform=1.,
    weight_tv_density=0.000016,
    weight_tv_k0=0.0,
    lrate_deformation_field=1e-4,
    pg_scale={pg_scale},
)

fine_model_and_render = dict(
    num_voxels={num_voxels}**3,
    num_voxels_base={num_voxels}**3,
    rgbnet_dim=12,
)
'''


def write_config(args) -> Path:
    corpus = Path(args.corpus).expanduser().resolve()
    manifest_path = corpus / "nevo_corpus.json"
    if not manifest_path.is_file():
        raise FileNotFoundError(
            f"{manifest_path} not found -- run orbitnevo.prepare on this object first"
        )
    with open(manifest_path) as handle:
        manifest = json.load(handle)
    frame_num = args.frames if args.frames > 0 else int(manifest["frames"])
    if frame_num > int(manifest["frames"]):
        raise ValueError(
            f"corpus holds {manifest['frames']} frames, cannot train {frame_num}"
        )

    # Progressive scaling checkpoints have to land inside the iteration budget;
    # DVGO doubles the grid at each and a checkpoint past N_iters silently means
    # the final grid is never reached.
    scales = [int(args.fine_iters * fraction) for fraction in (0.125, 0.25, 0.375)]
    body = CONFIG_TEMPLATE.format(
        expname=args.expname,
        basedir=str(Path(args.output_root).expanduser().resolve()),
        datadir=str(corpus),
        frame_num=frame_num,
        coarse_iters=args.coarse_iters,
        coarse_iters_p=max(1, args.coarse_iters * 3 // 5),
        fine_iters=args.fine_iters,
        fine_iters_p=args.fine_iters_p if args.fine_iters_p > 0 else args.fine_iters,
        tv_before=int(args.fine_iters * 0.75),
        pg_scale=scales,
        num_voxels=args.num_voxels,
        white_bkgd=bool(args.white_bkgd),
    )
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    path = CONFIG_DIR / f"{args.expname}.py"
    path.write_text(body)
    print(f"wrote {path}", flush=True)
    return path


def run_training(args, config_path: Path) -> int:
    environment = dict(os.environ)
    environment["LD_LIBRARY_PATH"] = os.pathsep.join(
        [str(RERF_ROOT / "ac_dc"), environment.get("LD_LIBRARY_PATH", "")]
    ).rstrip(os.pathsep)
    environment["PYTHONPATH"] = os.pathsep.join(
        [str(RERF_ROOT / "ac_dc"), str(RERF_ROOT), environment.get("PYTHONPATH", "")]
    ).rstrip(os.pathsep)
    environment.setdefault("CUDA_HOME", "/usr/local/cuda-12.4")
    environment["PATH"] = os.pathsep.join(
        [str(Path(environment["CUDA_HOME"]) / "bin"), environment["PATH"]]
    )
    environment.setdefault("TORCH_CUDA_ARCH_LIST", "8.9")
    environment.setdefault("CC", "/usr/bin/gcc-11")
    environment.setdefault("CXX", "/usr/bin/g++-11")
    environment["CUDA_VISIBLE_DEVICES"] = str(args.gpu)

    command = [
        sys.executable,
        "run.py",
        "--config",
        str(config_path),
        "--start_frame",
        str(args.start_frame),
        "--end_frame",
        str(args.end_frame),
        "--i_print",
        str(args.print_every),
    ]
    if args.render_test:
        command.append("--render_test")
    print("+ " + " ".join(command), flush=True)
    return subprocess.call(command, cwd=str(RERF_ROOT), env=environment)


def parse_args(argv=None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--corpus", required=True, help="output of orbitnevo.prepare")
    parser.add_argument("--expname", required=True)
    parser.add_argument("--output-root", default="~/nevo_runs")
    parser.add_argument("--frames", type=int, default=0, help="0 = all in the corpus")
    parser.add_argument("--start-frame", type=int, default=0)
    parser.add_argument("--end-frame", type=int, default=-1)
    parser.add_argument("--num-voxels", type=int, default=160,
                        help="cube root of the fine-stage voxel budget")
    parser.add_argument("--coarse-iters", type=int, default=5000)
    parser.add_argument("--fine-iters", type=int, default=8000)
    parser.add_argument("--fine-iters-p", type=int, default=0,
                        help="iterations for P-frames; 0 = same as --fine-iters")
    parser.add_argument("--white-bkgd", action="store_true",
                        help="composite the corpus onto white instead of its native "
                             "black. Off by default: training on white bakes a whitish "
                             "fringe into the silhouette that shows against any darker "
                             "background, and makes these pixels non-comparable with "
                             "baselines/Vega, which trains on black")
    parser.add_argument("--gpu", type=int, default=0)
    parser.add_argument("--print-every", type=int, default=1000)
    parser.add_argument("--render-test", action="store_true")
    parser.add_argument("--config-only", action="store_true")
    return parser.parse_args(argv)


def main(argv=None) -> int:
    args = parse_args(argv)
    config_path = write_config(args)
    if args.config_only:
        return 0
    return run_training(args, config_path)


if __name__ == "__main__":
    raise SystemExit(main())
